<?php

/**
 * declare(strict_types=1); missing by design
 * This file is generated by kanti/json-to-class
 */

namespace Kanti\GeneratedTest;

use Kanti\GeneratedTest\Data\A;
use Kanti\JsonToClass\v2\Attribute\RootClass;

#[RootClass]
final readonly class Data
{
    public function __construct(
        public A $a,
    ) {
    }
}
