<?php

/**
 * declare(strict_types=1); missing by design
 * This file is generated by kanti/json-to-class
 */

namespace Kanti\GeneratedTest\Data;

use Kanti\GeneratedTest\Data;
use Kanti\JsonToClass\v2\Attribute\RootClass;

#[RootClass(Data::class)]
final readonly class A
{
    public function __construct(
        public string $b,
        public string $c,
    ) {
    }
}
